### ISSUE TITLE
License infringement

### ISSUE THREAD

**Issue by Moustachauve** [dim0147/Cookie-Editor#1]
Hello @dim0147,

This repository does not respect the licensing term of my project, Cookie-Editor.

Can you please adjust your project to follow the rules here: https://github.com/Moustachauve/cookie-editor/blob/master/LICENSE
please?

Otherwise I will have to take action against your project.

Thank you

**Comment by dim0147** [comment]
Hi, I have updated README File and add LICENSE from your link, not sure is correct, If not correct or missing something tell me how do I solve it, I really don't know much about license

**Comment by Moustachauve** [comment]
That's perfect for me, thank you very much for the quick reaction :)

As a suggestion for future project of yours, doing forks is much easier and can give you the easy option of suggesting your changes to the project. Some features like converting cookie string from http is very interesting for me :)
